// Register test
### Test 1: Register a new user (should succeed)
POST http://localhost:18080/register
Content-Type: application/json

{
    "username": "yash",
    "password": "password123"
}

### Test 2: Try to register the SAME user again (should fail)
POST http://localhost:18080/register
Content-Type: application/json

{
    "username": "yash",
    "password": "anotherpassword"
}

### Test 3: Send a request with a missing password (should fail)
POST http://localhost:18080/register
Content-Type: application/json

{
    "username": "yash"
}

// Login test
### Test 4: Log in with correct details (should succeed)
POST http://localhost:18080/login
Content-Type: application/json

{
    "username": "yash",
    "password": "password123"
}

### Test 5: Log in with wrong password (should fail)
POST http://localhost:18080/login
Content-Type: application/json

{
    "username": "yash",
    "password": "wrongpassword"
}

### Test 6: Log in with a user that doesn't exist (should fail)
POST http://localhost:18080/login
Content-Type: application/json

{
    "username": "notauser",
    "password": "password123"
}

# --- Messaging Tests ---

### Test 7: Register two new users for messaging
# @name registerUserA
POST http://localhost:18080/register
Content-Type: application/json

{
    "username": "userA",
    "password": "passwordA"
}

###
# @name registerUserB
POST http://localhost:18080/register
Content-Type: application/json

{
    "username": "userB",
    "password": "passwordB"
}


### Test 8: userA sends a message to userB (should succeed)
POST http://localhost:18080/send
Content-Type: application/json

{
    "sender": "userA",
    "recipient": "userB",
    "content": "Hello userB, this is a test!"
}


### Test 9: userB retrieves their messages (should show 1 message)
GET http://localhost:18080/getMessages?username=userB


### Test 10: userB retrieves messages again (should be empty now)
GET http://localhost:18080/getMessages?username=userB


### Test 11: userA tries to send a message to a non-existent user (should fail)
POST http://localhost:18080/send
Content-Type: application/json

{
    "sender": "userA",
    "recipient": "userC",
    "content": "Are you there?"
}